[package]
name = "version-system"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[features]
testutils = ["soroban-sdk/testutils"]
default = []

[dependencies]
soroban-sdk = "21.0.0"

[dev-dependencies]
soroban-sdk = { version = "21.0.0", features = ["testutils"] }
